version: 2
jobs:
    build:
        working_directory: ~/mtg-cube
        docker:
            - image: circleci/node:10.12-browsers
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: Show current directory
                command: pwd
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Linting
                command: npm run lint
            - run:
                name: Testing
                command: npm run test
            - run:
                name: Building
                command: npm run build
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist
                    - package.json
                    - firebase.json
                    - .firebaserc
    deploy:
        docker:
            - image: circleci/node:chakracore-8.11-browsers-legacy
        working_directory: ~/project
        steps:
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Install Firebase
                command: npm install --save-dev firebase-tools
            - run:
                name: Deploy Master to Firebase
                command: npm run deploy

workflows:
    version: 2
    default_workflow:
      jobs:
      - build
      - deploy:
          requires:
              - build
          filters:
              tags:
                  only: /^v*/
